# ALGO-UmbrelOs-App-Store/algo-store-gemini-trading-agent/docker-compose.yml
# @author: Memba Co.

version: '3.8'

services:
  gemini-agent:
    # ARTIK BU SATIRI KULLANIYORUZ:
    image: ghcr.io/membaco/gemini-agent-web:latest # DEĞİŞİKLİK: İmaj adı 'gemini-agent-web' yerine 'gemini-trading-agent' olabilir, GHCR'de nasıl isimlendirdiğinize dikkat edin. Yukarıdaki yml 'gemini-agent-web' olarak isimlendirir.
    
    # BU SATIRI SİLİYORUZ:
    # build: . 
    
    restart: unless-stopped
    
    volumes:
      - ./data:/app/data
      
    ports:
      - "8080:8000"
      
    networks:
      - gemini-agent-net

networks:
  gemini-agent-net:
    driver: bridge